### ISSUE TITLE
Unable to redirect to external site

### ISSUE THREAD

**Issue by gtrentini** [gridonic/statamic-redirects#2]
Trying to redirect a page to some other sub/domain fails.
Ex.
`/company/labs:
  to: 'https://blog.mysite.com'
  status_code: 301
  locale: null
  retain_query_strings: true
  start_date: null
  end_date: `null``

**Comment by wanze** [comment]
Hi @gtrentini 

The latest commit adds support for external redirect targets. Could you download the latest version from GitHub and test if everything works correctly? I'll create a new release afterwards. Thank you!

Cheers

**Comment by wanze** [comment]
Redirects to external URLs has been released with `1.1.0`. 🙌

**Comment by gtrentini** [comment]
Sorry for the delay. Confirming that its working correctly.

Thanks!
