### ISSUE TITLE
Disable RedirectsLogger

### ISSUE THREAD

**Issue by o1y** [gridonic/statamic-redirects#3]
Thanks for your great add-on! Is there a way to disable the ``RedirectsLogger``? It would be great to have a setting to disable that feature :)

**Comment by wanze** [comment]
Hi @o1y 

Thanks for your feedback! At the moment it is only possible to disable the logging of `404`s. By disabling the `RedirectsLogger`, the module would no longer log how many times a redirect has been executed. Is this correct? :) I think we can easily introduce a toggle for this behaviour. 

Cheers

**Comment by o1y** [comment]
Hey @wanze
 
Yes, this is absolutely correct. I don't need the `RedirectsLogger` on my production system where the control panel is disabled. On the staging system where content changes happen there is no need to log my own redirects :)

Thanks!

**Comment by wanze** [comment]
Hi @o1y,

This feature has been released in version [1.3.0](https://github.com/gridonic/statamic-redirects/releases/tag/v1.3.0), you can disable the logging of redirects in the addon configuration.

Happy christmas! 🎄

**Comment by o1y** [comment]
Great! Thanks so much! Happy new year 🚀
