### ISSUE TITLE
Plans for v3

### ISSUE THREAD

**Issue by that0n3guy** [gridonic/statamic-redirects#6]
Hey,

What are your plans for v3?   I know a lot of folks are ramping up their v3 migration for add-ons.

I look forward to an update.

**Comment by sg-modlab** [comment]
Interested in this as well.

**Comment by plompd** [comment]
Yes, I'd like to know also.

**Comment by wanze** [comment]
Hi everyone,

As you probably already know, there now is a sophisticated redirects addon available for Statamic 3: https://statamic.com/addons/rias/redirect

Therefore we decided to not upgrade this addon for Statamic 3, as it does not make much sense to have two addons offering the same functionality. However, we will keep supporting this addon for Statamic 2.

Cheers
